# docker-compose.yml
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=base
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        command: redis-server --save ""

volumes:
    postgres-data:
        driver: local